### ISSUE TITLE
Generated fonts are rejected by the OpenType Sanitizer

### ISSUE THREAD

**Issue by jfkthame** [be5invis/Iosevka#114]
The generated font files currently deployed at https://be5invis.github.io/Iosevka/ are rejected by the OTS font validator/sanitizer tool[1]:

```
$ ot-sanitise iosevka-regular.ttf 
WARNING: cmap: subtable 1 with platform ID 0, encoding ID 3, language ID 0 following subtable with platform ID 3, encoding ID 1, language ID 0
ERROR: Layout: glyph range is overlapping.in range 5
ERROR: Layout: Failed to parse backtrack class defn table in chain context format 2
ERROR: Layout: Failed to parse chaining context format 2 subtable
ERROR: Layout: Failed to parse lookup subtable 5
ERROR: Layout: Failed to parse subtable 0
ERROR: Layout: Failed to parse lookup 3
ERROR: GSUB: Failed to parse lookup list table
Failed to sanitise file!
```

AFAICS, the checks in the tool are correct, implying that the font generation is faulty and results in tables that do not conform to the OpenType spec.

[1] https://github.com/khaledhosny/ots/

**Comment by be5invis** [comment]
Fixed by otfcc 0.4.4 and version 1.9.5. Closed.

**Comment by jfkthame** [comment]
Thanks for fixing this so quickly! I can confirm version 1.9.5 is not rejected by OTS.

The warning about incorrectly sorted entries in the 'cmap' directory still occurs; this is less important than the GSUB problem, as OTS is able to fix it and accept the font, but it would be good to correct this at the source as well.
