### ISSUE TITLE
Add currency symbol please

### ISSUE THREAD

**Issue by illusive-man** [be5invis/Iosevka#156]
Can you make Russian Ruble currency symbol (U+20BD or &#8381;) please? At the moment it's not present in your font and substitute is ugly. Your font is awesome, but without Iosevka-stylized currency symbol I can't use it at full. Thank you in advance!

**Comment by be5invis** [comment]
Fixed by #157. Closed.

**Comment by illusive-man** [comment]
I'm sorry, I'm new to GitHub but why my request was closed with currency symbol still missing? Downloaded latest version but there's nothing changed. I'm using it on Windows machine if that's matter.

**Comment by be5invis** [comment]
@illusive-man 
**It's already in. Just wait for the next version, OK?**

**Comment by illusive-man** [comment]
Sure, thank you very much!
