### ISSUE TITLE
Heavy-weight U+025a top-arc width depends on cv30

### ISSUE THREAD

**Issue by pv4** [be5invis/Iosevka#1587]
The issue is similar to #1525.

On the gif attached the image is being changed between cv30=1 and cv30=2. The middle column is 16.3.6, the right column is 18.0.0. It's visible that in 16.3.6 the top-arc had the same width between the cv30 values while in 18.0.0 the top-arc is wider in cv30=1 than in cv30=2.

![u025a](https://user-images.githubusercontent.com/2502094/223529215-b37bed75-9766-48bb-a594-0a7b794f49b5.gif)

I'm sorry that I didn't test the issue against 20.0.0, but can it matter for this issue? If it's critical then please write about that and I will retest against 20.0.0.

**Comment by be5invis** [comment]
I think it is already fixed.

**Comment by pv4** [comment]
As of 21.0.0 it is not fixed. Moreover, I discovered the plain latin e (and many derived glyphs if not all) are affected as well. I guess it's related.

![e](https://user-images.githubusercontent.com/2502094/224582763-7da5c90e-7b85-4c36-933a-7d71becf2ca8.gif)

**Comment by be5invis** [comment]
Fixed
